name: Run
on: 
  workflow_dispatch:
    inputs:
      params:
        required: false
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: prepare
        run: run() {
          	local command=""
          	local arg=""
          	for arg in "$@"; do
           		if [[ $arg != "--" ]]; then
           			command+="$arg "
          		else
          			eval "$command"
          			command=""
          		fi
          	done
          	eval "$command"
         }
      - name: run
        run: run ${{ github.event.inputs.params }}	
